package UI.panes.WorkflowDashboards;

import ij.ImagePlus;
import ij.gui.ImageCanvas;
import ij.gui.Plot;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Dashboard for displaying aligned image stacks and alignment results.
 */
public class AlignStackDashboard extends JPanel {

    private final JTabbedPane tabs = new JTabbedPane();

    public AlignStackDashboard() {
        super(new BorderLayout());
        add(tabs, BorderLayout.CENTER);
    }

    /**
     * Adds a new aligned stack + results CSV to the dashboard.
     * @param imp The aligned ImagePlus stack to display.
     * @param resultCSV The results CSV generated by the alignment.
     */
    public void addAlignedStackWithResults(ImagePlus imp, File resultCSV) {
        if (imp == null) return;

        // --- Parse CSV dynamically ---
        File cleanCSV = new File(resultCSV.getParent(), "CLEANED_" + resultCSV.getName());
        List<Double> slices = new ArrayList<>();
        List<Double> dx = new ArrayList<>();
        List<Double> dy = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader(resultCSV));
            PrintWriter pw = new PrintWriter(new FileWriter(cleanCSV))) {

            String headerLine = br.readLine(); // original header
            if (headerLine == null) return;

            String[] headings = headerLine.split(",");
            int sliceCol = headings.length - 3; // second last column
            int dxCol = headings.length - 2;    // last column
            int dyCol = headings.length - 1;

            // write cleaned header
            pw.println("Slice,Dx,Dy");

            String line;
            while ((line = br.readLine()) != null) {
                String[] tokens = line.split(",");
                if (tokens.length < 3) continue;

                double sliceVal = Double.parseDouble(tokens[sliceCol]);
                double dxVal = Double.parseDouble(tokens[dxCol]);
                double dyVal = Double.parseDouble(tokens[dyCol]);

                slices.add(sliceVal);
                dx.add(dxVal);
                dy.add(dyVal);

                pw.println(sliceVal + "," + dxVal + "," + dyVal);
            }

        } catch (IOException ex) {
            ex.printStackTrace();
            return;
        }

        // --- Create Plot ---
        double[] x = slices.stream().mapToDouble(Double::doubleValue).toArray();
        double[] yDx = dx.stream().mapToDouble(Double::doubleValue).toArray();
        double[] yDy = dy.stream().mapToDouble(Double::doubleValue).toArray();

        Plot plot = new Plot("Alignment Motion", "Slice", "Pixels");
        plot.setColor(Color.RED);
        plot.addPoints(x, yDx, Plot.LINE);
        plot.setColor(Color.BLUE);
        plot.addPoints(x, yDy, Plot.LINE);

        ImagePlus plotImp = plot.getImagePlus();

        // --- Aligned stack with slider ---
        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
        imageLabel.setVerticalAlignment(SwingConstants.CENTER);
        updateImageLabel(imageLabel, imp, 1);

        JScrollPane imageScroll = new JScrollPane(imageLabel);
        imageScroll.setPreferredSize(new Dimension(500, 600));
        imageScroll.setBorder(BorderFactory.createTitledBorder("Aligned Stack"));

        JSlider slider = new JSlider(1, imp.getStackSize(), 1);
        slider.addChangeListener(e -> updateImageLabel(imageLabel, imp, slider.getValue()));

        JPanel imagePanel = new JPanel(new BorderLayout(5, 5));
        imagePanel.add(imageScroll, BorderLayout.CENTER);
        imagePanel.add(slider, BorderLayout.SOUTH);

        // --- Plot panel ---
        JScrollPane plotScroll = new JScrollPane(new JLabel(new ImageIcon(plotImp.getImage())));
        plotScroll.setBorder(BorderFactory.createTitledBorder("Motion Plot"));
        plotScroll.setPreferredSize(new Dimension(500, 600));

        // --- Combine image + plot ---
        JPanel combined = new JPanel(new GridLayout(1, 2, 10, 10));
        combined.add(imagePanel);
        combined.add(plotScroll);

        // --- Add to tabs ---
        tabs.addTab(imp.getTitle() + " + Results", combined);
        tabs.setSelectedIndex(tabs.getTabCount() - 1);
    }

    // --- helper method ---
    private void updateImageLabel(JLabel label, ImagePlus imp, int slice) {
        imp.setSlice(slice);
        label.setIcon(new ImageIcon(imp.getProcessor().getBufferedImage()));
    }



}
